### ISSUE TITLE
Bug: There is no time conflict if time of lecture is the same & No conflict between Karlstr and Lothstr if there isnt more then 20 min time inbetween

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#101]
Bug: There is no time conflict if time of lecture is the same & No conflict between Karlstr and Lothstr if there isnt more then 20 min time inbetween

**Comment by heatsink** [comment]
Pull request is here https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/pull/159
