### ISSUE TITLE
CourseList: Make the Dropdown containing Departments more beautiful

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#112]
Do you want to take care of that @jusnelda you said today that you think this is not beautiful enough. 
I agree with you.

Notes about our talk:
- Move dropdown a little bit down that it docks to droppdown field.
- Add some color

**Comment by jusnelda** [comment]
I played around with it a little bit. But sadly the flutter dropdown API doesn't have more features to make it prettier. 
Maybe there is an alternative to this dropdown menu?

**Comment by failita** [comment]
I had a look at it a few weeks ago but I think we can only change the size for now.

**Comment by AndiAndreas** [comment]
There is the possibillity to use ShowDialog but this would need to much effort to do on the last day.
