### ISSUE TITLE
Translate Privacy Policy 

### ISSUE THREAD

**Issue by EduardBartolovic** [mobileappdevhm/dev-team-1-cie-app-in-flutter#124]
The Privacy is currently on German. It should be translated to english

**Comment by Poroma** [comment]
![screenshot_20180619-164609](https://user-images.githubusercontent.com/33720954/41604991-c2bfdc6c-73e0-11e8-9068-6060fd988436.png)
![screenshot_20180619-164612](https://user-images.githubusercontent.com/33720954/41604992-c2e5b234-73e0-11e8-84d1-a0e7da45b261.png)

If i use button to toggle between the language in the bottom of page. Is it gonna be ok?

**Comment by heatsink** [comment]
Could you make the text toggle between "Translate to English" and "Translate to German"?

**Comment by Poroma** [comment]
ok

**Comment by Poroma** [comment]
I think Tobias said that for translation, can I use deep translator, www.deepl.com for translation German privacy text that we already have?

**Comment by heatsink** [comment]
Looking at one of the paragraphs translated using www.deepl.com, the translation looks pretty good! I think we will be fine using it.

**Comment by EduardBartolovic** [comment]
Great
