### ISSUE TITLE
Discuss Theme Modifications

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#138]
Discuss whether a slight theme redesign would be an improvement (changing color of headers & header text, etc.)

**Comment by heatsink** [comment]
Proposal to modify main theme bar colors:
Current
<img width="279" alt="screen shot 2018-06-18 at 3 28 27 pm" src="https://user-images.githubusercontent.com/9795754/41538769-4ebc40be-730c-11e8-8676-f42db7bb0801.png">

1)
<img width="272" alt="screen shot 2018-06-18 at 3 27 50 pm" src="https://user-images.githubusercontent.com/9795754/41538790-5d89c0e4-730c-11e8-82de-fad625d473b3.png">
2)
<img width="281" alt="screen shot 2018-06-18 at 3 27 34 pm" src="https://user-images.githubusercontent.com/9795754/41538797-61539ec0-730c-11e8-8a32-f46d5653855d.png">

**Comment by heatsink** [comment]
Proposal to change theme bar text:
I think it is already clear from the tabs below which page we are on, I think it might look good to display the app title instead. What do you guys think?
<img width="276" alt="screen shot 2018-06-18 at 3 30 19 pm" src="https://user-images.githubusercontent.com/9795754/41538901-a5d82eee-730c-11e8-89f9-370c41592c0e.png">

**Comment by AndiAndreas** [comment]
Design 1. As written in #174. Its red, but I think we should take this. Looks better than gray original one.

**Comment by RedTo** [comment]
Closing of the pull request was to fast :-/

I'm sorry for beeing rude. Shouldn't be, you did and doing a very good job...
Just wanted to be sure, that this change is okay for nearly everybody.

I agree: Red background + whit font color looks best.

**Comment by heatsink** [comment]
Don't apologize, no one was being rude! All is good!

Also, what do you guys think about renaming our "Settings" tab to "Profile"
    and "Timetable" to "Schedule"?

This has the added benefit of better fitting the tab text for small screens like iPhone 5 without changing the already small font size.

Before
<img width="229" alt="screen shot 2018-06-19 at 1 00 47 pm" src="https://user-images.githubusercontent.com/9795754/41593603-ed79ab10-73c0-11e8-89c1-f3e8e33967dc.png">

AFter
<img width="227" alt="screen shot 2018-06-19 at 1 00 20 pm" src="https://user-images.githubusercontent.com/9795754/41593615-fbb0f1ca-73c0-11e8-8dd8-5e6347d76f21.png">

**Comment by AndiAndreas** [comment]
👍 Good one

**Comment by RedTo** [comment]
I'm with you! :-)

**Comment by RedTo** [comment]
New Theme is already implemented.
