### ISSUE TITLE
Filter Cources List

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#14]
Filter Cources List by passing filter parameters to the presenter.

There is no UI for the filter since yet.

**Comment by heatsink** [comment]
Closing, duplicate of the combination of (https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/51, https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/45)
