### ISSUE TITLE
Pushing Course Data to Nine for registration lottery

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#141]
(Depends on Nine to be fully implemented, but the majority skeleton code can be completed to filter the favorited course data, build back into json, build the post request with the body, and sent to a temporary url)

**Comment by RedTo** [comment]
Since yesterday it should be possible to push to the lottery. I just heard that a few hours ago...

**Comment by RedTo** [comment]
Please change the corresponding icon on github pages if this is implemented. Just ask if you need help to identify the right one.

**Comment by heatsink** [comment]
If anyone knows or can point me to information that specifies what kind of body nine expects from us in order to register for the lottery I could implement this.

Also, if I were to make a successful request right now for testing what would happen? Does this data get sent to Primuss or something yet?

**Comment by orb1005** [comment]
@heatsink  At the bottom of the following page you can find the information on how to register for courses
https://github.com/mobileappdevhm/CiEApp/wiki/Course-API

If you test this function right now your dummy user will register to the courses. According to mr. hinz there's also an api call to unsubscribe courses, but it has no functionality yet.

**Comment by heatsink** [comment]
I'll do this task but I'm busy until the end of Friday. If anyone wants to get this out earlier, feel free to take this task from me.

@orb1005 Thanks, I tested the post request out on Postman, works great.

**Comment by heatsink** [comment]
(Note: including https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/241 in this commit)

**Comment by RedTo** [comment]
Are you sure that this is already done?

**Comment by heatsink** [comment]
Oops, meant to only close the other issue. There's a pull request for this now.

**Comment by RedTo** [comment]
Finished, see #266
