### ISSUE TITLE
UI - Style Pull down to Refresh

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#145]
Finalize the UI for the Pull down to Refresh indicator.

**Comment by AndiAndreas** [comment]
Isnt this donw aready @heatsink

**Comment by heatsink** [comment]
Well the functionality is there, I was thinking we should figure out what might look down for the little "Pull down to Refresh" container at the top of the courseList since the blue container and text doesn't really fit in right now. (We can also decide if we even want to show this text and container at all and only have the refresh functionality).

Should be a pretty fast issue to finish.

**Comment by RedTo** [comment]
I think it would be nice to maybe have a small text directly under the title. Maybe something like: "Pull down to refresh". If the user than swipes down, the reload icon is shown and the reload is triggered.

What do you think? But maybe don't wast to much time for this. A simple solution should be enough.

**Comment by heatsink** [comment]
This functionality already exists as you described, this issue is intended for improving the current UI design because I'm not sure what would look best.

**Comment by AndiAndreas** [comment]
Just take same blue as used everywhere. Rest looks good for me. Then close and foreget 🤣

**Comment by heatsink** [comment]
Sounds good to me lol

**Comment by heatsink** [comment]
merged
