### ISSUE TITLE
Favorites Page - Make the un-favorite action more difficult

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#149]
Currently, it is easy to misclick to remove a course from the favorites page. Make this action more difficult somehow. Perhaps we can add an "are you sure" popup to unfavorite a course.

Alternatively, we can leave the favorite circle unfilled after clicking and add a button to "Un-favorite these courses"

**Comment by RedTo** [comment]
I like the way Andi did this! 👍
