### ISSUE TITLE
Calendar - Export Functionality

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#156]

**Comment by RedTo** [comment]
@heatsink I'm sorry. I have not found a fitting solution, maybe you have another idea?

I tried a different permission package and a newer ios version. Maybe the old package with the new ios version is a try worth? Would be great if you could try it locally!

**Comment by RedTo** [comment]
Seams like there is no way to implement this function into iOS without writing Swift code... We will not investigate more time into this.
