### ISSUE TITLE
Re-implement overflow protection on courseDetails page

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#167]
Related to https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/164,
the master branch wasn't compiling for iOS because it didn't like something about the way we used expanded in the widget for the description page.

Therefore, part of the commit was reverted temporarily.

Investigate this further, and implement in a different way that makes iOS happy.

**Comment by AndiAndreas** [comment]
This is yours because the current approach wasnt compiling on IOS but worked on Android.

**Comment by heatsink** [comment]
merged
