### ISSUE TITLE
wrong password popup doesn't show up 

### ISSUE THREAD

**Issue by orb1005** [mobileappdevhm/dev-team-1-cie-app-in-flutter#218]
If the password has a length of seven symbols and is wrong the app show an error message to the user
![image](https://user-images.githubusercontent.com/15432349/41790158-ee9a31ac-7651-11e8-9e90-ed13830d1cd6.png)

Like this 
![image](https://user-images.githubusercontent.com/15432349/41790211-10a60a3c-7652-11e8-9a7b-97ed83365e21.png)

However if a password is wrong  and longer than seven symbols I only get an error message in android studio

![image](https://user-images.githubusercontent.com/15432349/41790281-4b2c4676-7652-11e8-8a74-2ea2d31fff3e.png)

**Comment by RedTo** [comment]
Good error description! Gotcha :-)

**Comment by orb1005** [comment]
@RedTo Thanks for taking care of this

**Comment by RedTo** [comment]
Fixed with #222.
