### ISSUE TITLE
Lecturer info

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#239]
At the moment no lecturer info is showed in the app.
There would be the possibility to get that information from nine via a second/third request.
 - https://nine.wi.hm.edu/api2/Lecturer/GetAllLecture will get all lecturers
 - inside this json we could search for the name and than get the missing email

A good approach would be to store this info like we do with the courses, I guess.

**Comment by heatsink** [comment]
I'll do this task but I'm busy until the end of Friday. If anyone wants to get this out earlier, feel free to take this task from me.

**Comment by RedTo** [comment]
Finished! 👍
