### ISSUE TITLE
Lotterybutton text

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#241]
The text of the lottery button does not always go with the situation.
- 'Already send' appears if guest is logged in

Maybe it would be possible to get when the lottery is open and when it is closed and only during this period allows to send the data.

**Comment by heatsink** [comment]
Will be including this in https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/141
