### ISSUE TITLE
Building Error iOS + Firebase on 1st build

### ISSUE THREAD

**Issue by jusnelda** [mobileappdevhm/dev-team-1-cie-app-in-flutter#242]
Frau Socher tried to build out app and got the following Error: 

> 'The default Firebase app has not yet been configured' (in Android Studio on a Mac) and with XCode: 'Library not found for -lFirebaseCore'

Our latest version builds on my iPhone just fine, but it's probably different if you build the app initially...

**Comment by heatsink** [comment]
Inside the project directory, do
1. `open ios/Runner.xcworkspace/`to open the XCode project
In xcode, 

2. > "File"->"Add files to Runner"

3. > add the "GoogleService-Info.plist"

 file. It is located in the ios directory in the project

https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/pull/219
The reason only the configuration file was added was that Xcode still wouldn't link the file if I made the changes and committed the IOS changes.

**Comment by jusnelda** [comment]
Unfortunately Frau Socher still couldn't build the app. I'll help her later.

**Comment by RedTo** [comment]
Is it working now?

**Comment by RedTo** [comment]
@jusnelda What's the current progress on this?

**Comment by heatsink** [comment]
I've done a clean install starting with cloning the repository. It builds fine for me after starting with our normal XCode configuration. I think we can close unless anyone else has a different story

**Comment by RedTo** [comment]
Thank you Sean!
