### ISSUE TITLE
Bug: contact button on privacy page without functionality

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#246]
Bug: contact button on privacy page without functionality

**Comment by RedTo** [comment]
Whom we should contact there, any ideas?

**Comment by EduardBartolovic** [comment]
I have some ideas:  Mrs Socher, Cie Team or the official Datenschutzbeauftragten of the HM

**Comment by AndiAndreas** [comment]
International office
