### ISSUE TITLE
Background Image in App Instruction should be lighter.

### ISSUE THREAD

**Issue by EduardBartolovic** [mobileappdevhm/dev-team-1-cie-app-in-flutter#248]
Background Image in App Instruction should be lighter.

Its really difficult to read the text

**Comment by jusnelda** [comment]
What do you mean by App Instruction exactly?

**Comment by failita** [comment]
It’s the first page. You can also access it on the Profile page.

**Comment by RedTo** [comment]
Please have a look at the latest version of the app. (Reinstall than go, for example to course list)

**Comment by jusnelda** [comment]
Alright I found it. 👍
