### ISSUE TITLE
Maps.dart not all Maps showing up

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#29]
Simetimes when I Start the App not all Maps are showing up. It is Random which are shown which not.

**Comment by AndiAndreas** [comment]
![photo_2018-05-23_21-47-23](https://user-images.githubusercontent.com/6030353/40447457-ec85ba6c-5ed2-11e8-9e53-5d11c9336c98.jpg)

**Comment by RedTo** [comment]
Would be great if this could be finished in Sprint 1. What do you think?

**Comment by AndiAndreas** [comment]
Can be closed now. Ty Sean for fixing.
