### ISSUE TITLE
Lecturer Information

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#291]
Not all information of a lecturer is given or available, as we can see on the response of https://nine.wi.hm.edu/api/v2/apps/cie/courses/WiSe%202018

It would be possible to get all the data from https://nine.wi.hm.edu/api/Lecturer/GetAllLecture. Sometimes we only get the lastname, so we would have to search for lecturer A from "...courses" in "...GetAllLecture", but if we get more than one result (some lecturers share their lastname) we would have a problem.

Maybe it would be better to use the profile links instead of the email addresses?!

**Comment by RedTo** [comment]
Another problem: Not every lecturer has defined a profile page.

**Comment by RedTo** [comment]
@gsocher What do you think is the best option here?

At the moment we are trying to get the mailaddress, if we do not get one and the contact button is pressed, the user is informed, that there is no mailaddress saved.

**Comment by gsocher** [comment]
I think it is a good idea to show an error message if the user has pressed the contact button for a lecturer with no email address provided. For some lecturers (especially 'Lehrbeauftragte') there is no way to contact them ahead of time.
