### ISSUE TITLE
Department of old courses

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#295]
Should we display the department of the old courses similar to course list?

-> old courses does not really have a department set (it is FK 13 by default)
-> sometimes there is a module set with different information (should we use this, or what exactly are those modules?)

**Comment by RedTo** [comment]
@gsocher what do you think about the following:

- should we display department under the course title?
![image](https://user-images.githubusercontent.com/15648487/45842650-9b2e3c80-bd1d-11e8-9e31-b655294e51b4.png)
Maybe like it is if a course is selected in course history:
![image](https://user-images.githubusercontent.com/15648487/45842671-b1d49380-bd1d-11e8-9886-37cd15104421.png)

- what department should be shown at the old courses, because they are all listed under DP 13 but have a module set with a different DP

**Comment by gsocher** [comment]
I would not show the department info. I would only show the number of ECTS. Does a student care about the department?

**Comment by RedTo** [comment]
I guess it is only important for the certificates. As far as I now, theoretically one course of department 13 has to be taken for the cie certificate. For the iec all courses should be from department 3 (and 2 ects from 13?!), but I'm not quite sure about it.

Maybe that's the only point where it is important...

**Comment by gsocher** [comment]
I think that you only need 15 ECTS in courses in English from any department. I don't think that the department mattters.
