### ISSUE TITLE
Changes in test/views/start_test.dart

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#30]
test/views/start_test.dart 

Please remove Test for Button "Courses in English". This is no Button.

**Comment by RedTo** [comment]
Maybe we should think about to do tests for this.
Click 'Start' -> Login page opens
Click 'Login' -> Tab pages opens
Click a tab -> tab page changes
etc etc etc ?!

**Comment by EduardBartolovic** [comment]
ich could do it

**Comment by RedTo** [comment]
closed for sprint one. New issues will follow
