### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#308]
Think about Firebase Analytics. If we want to use it, we have to create a project in the firebase console. And? I do not know exactly what else is to do, but we can find out.

**Comment by gsocher** [comment]
please reactivate. Invited you to Firebase Projects 'CiE App' (the CiE App which is released in Google Play) and 'CiE App V2'. I would update the CiE App relasesd in Google Play. Firebase analytics should then just word. You have access to the Google Play Console with your @hm.edu account. I also sent you an invitation to your other account.

**Comment by RedTo** [comment]
Firebase is implemented again.
We are tracking the following at the moment:
- start screen
- login screen
- courses screen
- map screen
- schedule screen
- favorites screen
- profile/settings screen
- taken courses screen
- privacy text opened
- instructions opend
- courses unsubscribed
- courses subscribed
- complete data fetched / updated (from instructions)

Please let me know if there is something else we should track, I will close this issue by now.

**Comment by gsocher** [comment]
great! Thanks.
