### ISSUE TITLE
Combine appointments of blocked courses

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#309]
If course (mainly blocked courses) have different appointments on the same day, for example on monday the course starts at 9am, the week after at 11am...

At the moment there are different entries in the schedule, maybe combine them to save some place.

**Comment by gsocher** [comment]
I would not do this for now. If there are multiple appointments in one day, may be there is a reason (e.g. different locations).

**Comment by RedTo** [comment]
The problem with the appointments is, that we do not know which room is used.

If we do the data fetching we get the following:
- description info (name, department, shortname etc)
- appointments (list of weekdays and start/end, for example: Mon 8.15-XXX, Mon 9.15-XXX ...)
- locations (list of rooms in campus)
- lecturer (list of lecturer with name, profile)
- dates (detailed information of above, for example: 01.10.2018 8.15-XXX, in room XXX, lecturer XXX)

So using appointments in the schedule has the advantage, that we can see on which weekday the lectures are hold and on which time, but we have to guess the room, campus and lecturer, if there are more than one.

On the otherside, if we would use the dates to display the schedule, it is very hard to display a schedule like we do yet, because we do not know on which weekday the lectures occure. Okay, we know them by looking closer at the date, but the problem here is, that we would have to look on all the given dates to get the a similar result. That's a heavy overload i guess.

I'm not quite sure what would be the best solution here.

**Comment by RedTo** [comment]
Will be fixed if #320 is implemented.
