### ISSUE TITLE
Bug: Profile Error 'Invalid Argument(s)'

### ISSUE THREAD

**Issue by gsocher** [mobileappdevhm/dev-team-1-cie-app-in-flutter#317]
Latest Release of CiE app shows error message for my profile (gudrun.socher@hm.edu)

**Comment by RedTo** [comment]
I guess this has something to do with the newly implemented level. Levels will not be set by lecturers.

So let's check if the data is available and Display or hide it.

**Comment by RedTo** [comment]
The problem occurs if no department or study information is set.
So usually NINE will ask the user to set some information, if this is not done there will be this error on the profile page.

Let's see what we can do...
