### ISSUE TITLE
Bug: All the maps shown are the same

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#33]
static const String RESOURCE_KARLSTRASSE ='images/karlstrasse.png';         
  static const String RESOURCE_LOTHSTRASSE ='images/karlstrasse.png';         
  static const String RESOURCE_PASING  ='images/karlstrasse.png';

**Comment by AndiAndreas** [comment]
Fixed wait for Pull Request

**Comment by RedTo** [comment]
Approved
