### ISSUE TITLE
CiEColor class

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#35]
Set up a own color class where we can specify our colors and reference it easily.

For example:
- Color.fromRGBA(...) is not very nice
- Colors.red is nice but maybe not always the right color

=> Solution would be something like CiEColor.red where we have defined red over Color.fromRGBA

**Comment by RedTo** [comment]
@AndiAndreas what do you think?

**Comment by AndiAndreas** [comment]
Good idea. Lets code :D

**Comment by RedTo** [comment]
Sprint 1 or 2?
