### ISSUE TITLE
Settings: Previous courses now showing up properly.

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#38]
On my device I can see only half of the first taken course. We should consider making this a clickable button.
Then display the courses in another view.

**Comment by RedTo** [comment]
Maybe a scrollable list would be a better approach here?!

**Comment by failita** [comment]
This is what we have for the moment.

![simulator screen shot - iphone x - 2018-06-05 at 08 37 16](https://user-images.githubusercontent.com/28138757/40959056-cc5fd89e-689b-11e8-87ff-9c18937e5a09.png)

![simulator screen shot - iphone x - 2018-06-05 at 08 37 24](https://user-images.githubusercontent.com/28138757/40959062-d2d34c38-689b-11e8-98e9-d6a31c8e379a.png)
