### ISSUE TITLE
Courses and Favourits not showing correctly when swiping between them

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#43]
When I start the app and swipe to the Favourits and then back to the Courses the app doesn't display the courses anymore. It displays the Favourits in the Courses tab. The other ways round works as well. See Picture.

![grafik](https://user-images.githubusercontent.com/6030353/40513464-25de6f38-5fa6-11e8-9a0d-488404c78300.png)

**Comment by RedTo** [comment]
Maybe a problem in this method: https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/blob/master/lib/views/tabs.dart#L88

**Comment by RedTo** [comment]
Can you please go more into detail?

I could not reproduce this issue. Selecting and unselecting works on both screens and also the courses are shown as expected.

![screenshot_1527421801](https://user-images.githubusercontent.com/15648487/40585526-e49916d4-61b4-11e8-8873-8dcb639b79c0.png)
Selected different favorits.

![screenshot_1527421806](https://user-images.githubusercontent.com/15648487/40585528-ec8cd8da-61b4-11e8-9801-6d9c534a8b05.png)
Showing all courses, comming from favorites tab.

**Comment by RedTo** [comment]
Got it. Swiping is the problem...
