### ISSUE TITLE
Favorites Page - Add time conflict UI functionality 

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#53]
Also, match the figma mocks more closely as shown below
<img width="379" alt="screen shot 2018-05-25 at 1 22 10 pm" src="https://user-images.githubusercontent.com/9795754/40542042-ae93187e-601e-11e8-87ad-bc9f21c85eda.png">

**Comment by heatsink** [comment]
Detection implemented on TimeTable and could be easily extended to favorites page in next sprint. Should be done after we figure out a better mock structure for courses between the courselist and timetable

**Comment by AndiAndreas** [comment]
Do we realy need this? We cant figure out what courses the user got from lottery. So we need to take the courses from Favourites Page. Then there is no need to add this functionality in Favourites Page as well.

**Comment by heatsink** [comment]
I was thinking that the reason for this to exist in the favorites page would be to just be a notification before a user registers for classes.

For example, if I favorite two courses that start at 8:15 on the same day, or in the current case where I register for two classes that are too far, I should be made aware that there is a time conflict before registering these classes.

However, if we're running out of time, I think it's fine to omit this in the release.

**Comment by RedTo** [comment]
I like the idea of @heatsink 
So let's see how many time is on friday morning :-)
