### ISSUE TITLE
Skip login

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#59]
If a user comes to login page and do not want to login there should be a possibility to skip the login.

My idea was to let the login button show 'Skip' if the user has not made any input and 'Login' if the user had already made some input to email or password field.

As an alternativ we can only check email and password if both are filled and skip if there was no input. But I think that's not really nice, because the UI should always tell the user whats happing...
Second alternativ would be to have another text below the login button 'Login as guest' or 'Skip without login' or something similar.

**Comment by RedTo** [comment]
@jusnelda What do you think fits best in the UI?

**Comment by jusnelda** [comment]
I like the idea of the button changing, but I'll think it'll be more intuitive to have an extra button with 'Login as guest'

**Comment by jusnelda** [comment]
Have a look at my new Login screen, is this like something you guys had in mind?
