### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by EduardBartolovic** [mobileappdevhm/dev-team-1-cie-app-in-flutter#62]
Goal is to achieve 80% Code coverage

**Comment by RedTo** [comment]
I'm not quite sure if a goal of 80% is to high, but let's try :-)

**Comment by RedTo** [comment]
If you like you can define more issues for testing. Maybe it's easier for others to give you a helping hand if the see on which tests they can work?! And you can close more issues 😄

**Comment by RedTo** [comment]
How would you like to go on with this issue? Just asking, because normally this could never be closed...

Have you thought about open more issues for testing (different smaller aims)?

**Comment by EduardBartolovic** [comment]
I think this is a good idea. Lets do it in the next Sprint :D
