### ISSUE TITLE
Try to open map on Android

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#66]
If I try to open one of the maps on Android the Applemap link is send to the browser. Google maps is opening because there is no apple maps installed, but I was just wondering why.

![screenshot_1527441814](https://user-images.githubusercontent.com/15648487/40588813-8e14ac72-61e3-11e8-8dbd-ee6897c42510.png)

If this is always the same, we could imagine to try to open only the apple maps?! But I think a better way would be to open g-Maps on Android and a-Maps on iOS as we wanted to.

**Comment by jusnelda** [comment]
I'll look into it asap! But I'll one of you guys to try it on android for me ;)

**Comment by RedTo** [comment]
Sure, just give it a try and write here. I gona test in on Android than.

**Comment by jusnelda** [comment]
So, when I tab the map on ios with googlemaps **NOT** installed it opens apple maps, 
**WITH** googlemaps installed it asks to open googlemaps and correctly opens googlemaps. 
So maybe somebody with an android phone should look into it. 
To make it work quickly just delete the query for apple maps...

**Comment by RedTo** [comment]
I will give it a try in the next days, thanks for trying out on iOS!

**Comment by AndiAndreas** [comment]
Closed with #119
