### ISSUE TITLE
UI improvment in Course Details

### ISSUE THREAD

**Issue by EduardBartolovic** [mobileappdevhm/dev-team-1-cie-app-in-flutter#69]
it would be cool if that heart icon is clickable.

I think if you read something about this course than you should be able to mark it from this page.
Otherwise the user must go back one side and then he can press the icon.

![screenshot_2018-05-28-15-13-08](https://user-images.githubusercontent.com/26791581/40617052-67175872-628d-11e8-8766-187b83f436f7.png)

**Comment by RedTo** [comment]
Agree!

**Comment by RedTo** [comment]
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/44 - duplicate
