### ISSUE TITLE
Store Users Email address instead of Username

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#77]
I just saw, that we are storing a username for each user at the moment. Do we need this information anywhere? Maybe it is a better approach to store the users email address.

I think we will need this to authenticate on the nine - api, don't we?
@orb1005 and @EduardBartolovic what do we need for authentication?

**Comment by EduardBartolovic** [comment]
We just talked to Prof. Hinz . The Username will be the email

**Comment by RedTo** [comment]
![grafik](https://user-images.githubusercontent.com/26791581/40980192-1ef53798-68d8-11e8-836e-7d2c1072eb47.png)

As we have discussed in #89 we should rename this function and also store the users email address instead of a username.
In other words:
- delete the above (we do not need a username)
- add email attribute + corresponding methods

**Comment by AndiAndreas** [comment]
already close #89
