### ISSUE TITLE
Create Screen - Settings/Profile

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#8]

**Comment by failita** [comment]
I'm not sure yet about 
- how we store user information, and
- how we can get the "enrolled course list"
probably add getEnrolledCourseList method(?) comparing IDs and create another widget similar to courseList/courseListItem (?), or if there is a simpler way(?), I need advice/help on this  @AndiAndreas

**Comment by AndiAndreas** [comment]
Just some Information:

I created a quick draft for the course list data store. There is still work to do.
The basic idea is to use dependency injection and data models to store Data. This allows us to create Tests with Mock objects easily.
To do this you have to create a model of your data. In my case Couse.dart in model folder, as far as I remember.
Then there is your dependency injector you have to create. Afterwards create Mock and Prod data store. Only mock should be done for now.  Don’t worry about getting real data in this Sprint.

Sean is using the List Widget for the favorite view as well. You may have a look at his code after he uploaded or talk to him. But as Tobi said: For now keep it simple and hardcode stuff if necessary. Make the UI running.
