### ISSUE TITLE
Course description

### ISSUE THREAD

**Issue by jusnelda** [mobileappdevhm/dev-team-1-cie-app-in-flutter#80]
On smaller phones (iphone SE) the course description should be scrollable: 

![course_description_bug](https://user-images.githubusercontent.com/33668127/40655283-24ff46d4-6341-11e8-9fa3-d4e5e5e5cf7e.PNG)

**Comment by AndiAndreas** [comment]
Could you guys take this? Iam still buys with other issues.

**Comment by failita** [comment]
I'm finding a solution for this.
if anyone gets there first, please go ahead.

**Comment by failita** [comment]
- wrapped the text in a scrollable widget and 
- get all info from the coursePresenter

![simulator screen shot - iphone x - 2018-06-07 at 17 22 14](https://user-images.githubusercontent.com/28138757/41109523-7fbde480-6a77-11e8-9fd8-88dc14fc1b01.png)

**Comment by RedTo** [comment]
@orb1005 Which one is the duplicate? #44 ?

**Comment by orb1005** [comment]
#44 was kind of duplicate, but I renamed #44 so it should be different now
