### ISSUE TITLE
Courses: Add room number and location to Courses/Lectures.

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#87]
For the timetable it is required to add room number and location to the courses / lectures.
Do you think adding room number to lecture and location to course is enough?
Or do you think both should be added to lecture?

Hmm I think adding it both to lecture is best. 

# **ONLY IMPLEMENT IN TIMETABLE BRANCH.**

![grafik](https://user-images.githubusercontent.com/6030353/40945587-cd1ee2da-6859-11e8-8665-c851041392d2.png)
This is just a sneak preview of the TImetable. Not finished yet!

**Comment by jusnelda** [comment]
I think it's good to have all the info like in the screenshot. Although I'd change the _location_ to _campus_ .

**Comment by RedTo** [comment]
I would agree with you @AndiAndreas but also @jusnelda is right (location -> campus).

Maybe it would be good to add a little separator between the courses?
