### ISSUE TITLE
Make buttons on login page functional

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#88]
There have to be some functionality be implemented to the buttons on the login page.

Login-Button:
 - check if mail is valid
 - check if password is valid
 - check if user exists and credentials are valid
 - set current user (not sure how we would like to do this)

No Account:
 - open default browser
 - navigate to create account page on nine

Login as Guest:
 - redirect to tabs
 - set current user to guest (not sure how we would like to do this)

Forgot password:
 - open default browser
 - navigate to forgot password page on nine

**Comment by orb1005** [comment]
I made a basic api call to nine. I just don't know where to store the full name. Also I don't validate the result in any way

**Comment by RedTo** [comment]
forgot to implement 'no account' and 'forgot password'
