### ISSUE TITLE
Username is Email

### ISSUE THREAD

**Issue by EduardBartolovic** [mobileappdevhm/dev-team-1-cie-app-in-flutter#89]
Inside the lib/presenter/currentUserPresenter.dart is the Username a combination of the first and lastname which is not right. please change it to Username. This is important for the login later on :D

**Comment by RedTo** [comment]
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/77 ?

**Comment by EduardBartolovic** [comment]
![grafik](https://user-images.githubusercontent.com/26791581/40980192-1ef53798-68d8-11e8-836e-7d2c1072eb47.png)

this should be the real username. not a combination of first and lastname

**Comment by RedTo** [comment]
Okay, I understand. But in #77 you mentioned, that there is no need for a username.

To clarify: would you save the users email in username or create a different one?
Maybe it would be better to rename username to mail and than store the email there, would this also be ok for you?

**Comment by RedTo** [comment]
Nevertheless for me #77 and #89 are duplicates, aren't they?

**Comment by failita** [comment]
It's meant to get user's full name. We could change the name of the function to "getCurrentUserFullname" and create another one to get the username.

**Comment by EduardBartolovic** [comment]
They are kind of duplicated.

either we use username to store the email or we rename it to mail.

**Comment by RedTo** [comment]
I'm closing this and will put all the information in #77 .
