### ISSUE TITLE
Unittesting

### ISSUE THREAD

**Issue by RedTo** [mobileappdevhm/dev-team-1-cie-app-in-flutter#9]
Think about splitting it up or create it for all screens - your choice ;-)

**Comment by AndiAndreas** [comment]
Course list feature is created with mvp pattern and DI. Testing should be easy for this feature.

**Comment by RedTo** [comment]
The login screen has some methods for validation. At the moment they are not used.
But we can think about already writing tests for them.

**Comment by EduardBartolovic** [comment]
kann ich gerne noch morgen machen
