### ISSUE TITLE
Course List - Error when tap on search button, go to another screen, and come back. 

### ISSUE THREAD

**Issue by failita** [mobileappdevhm/dev-team-1-cie-app-in-flutter#91]
I got this error when I 
tap on search button -> tap on search box (and it appears red) -> tap on another menu -> tap back to course list menu 

![simulator screen shot - iphone x - 2018-06-07 at 19 45 09](https://user-images.githubusercontent.com/28138757/41116922-f0b7ffe0-6a8b-11e8-9b2b-1cb70c8b1c57.png)

**Comment by RedTo** [comment]
This error only occures if the keyboard does not open quickly enough or stay closed. Maybe it has something to do with the autofocus?

**Comment by AndiAndreas** [comment]
OK ran over it by accident. Now i know what is meant.

**Comment by AndiAndreas** [comment]
Tried to fix this by turning off autoFocus and focusNode. But this isnt solving this issue.

**Comment by heatsink** [comment]
merged
